---
title: "Grupa A"
author: "Julianna Waluś"
date: "7 12 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 999, digits=3)  #wyłączam notację naukową, dajemy 3 miejsca po przecinku
library(tidyverse)   #pakiet wranglingowy, z fajkami i grafiką ggplot2
library(rmdformats)  #pakiet z szablonami Markdown
library(magrittr)   # pakiet do fajek
library(lubridate)  # pakiet do operacji na datach
library(dplyr)
library(tidyr)
library(naniar)
library(visdat)
library(dlookr)
library(ggplot2)
library(rmdformats)
library(validate)
library(validatetools)
library(dcmodify)
library(errorlocate)
library(deductive)
library(VIM)
library(simputation)
library(lumberjack)
library(ISLR) 
library(dlookr)
library(xts)
library(quantmod)
library(ROCR)
library(Information)
library(scorecard)
library(readr)
agencja_nieruchomosci <- read_csv("agencja_nieruchomosci.csv")
View(agencja_nieruchomosci)
getwd()
```

```{r}
### Wprowadzenie do projektu
#Projekt z przedmiotu "analiza danych" będzie koncentrował się na kompleksowej analizie danych z agencji nieruchomości. Będziemy pracować na zestawie danych zawierającym 13 kluczowych zmiennych, w tym cenę nieruchomości, powierzchnię, liczbę sypialni i łazienek, liczbę pięter, dostępność połączenia z główną drogą, obecność pokoju gościnnego, piwnicy, systemu ogrzewania wody, klimatyzacji, liczby miejsc parkingowych, lokalizacji w preferowanym obszarze oraz statusu umeblowania. Naszym celem będzie czyszczenie, przygotowanie i poddanie analizie tych danych do dalszych badań, aby lepiej zrozumieć trendy i wzorce w branży nieruchomości.

```

```{r}
attach(agencja_nieruchomosci)
braki_danych <- colSums(is.na(agencja_nieruchomosci))
braki_danych
#Weryfikacja danych wykazała, że nasze zbiory są kompleksowe i nie zawierają żadnych braków danych. Ta sytuacja umożliwia nam pełne skorzystanie z dostępnych danych do przeprowadzenia analizy i uzyskania wiarygodnych wyników.

agencja_nieruchomosci <- agencja_nieruchomosci %>%
  mutate(area_m2=area/10.764) %>%
  relocate(area_m2, .after=area)
#Dodanie danych powierzchni w m2

agencja_nieruchomosci <- agencja_nieruchomosci %>%
  mutate(Cena_za_m2=price/area_m2) %>%
  relocate(Cena_za_m2, .after = price)
```


```{r}
#Statystki poszczególnych zmiennych
summary(agencja_nieruchomosci)

```


```{r}

boxplot(agencja_nieruchomosci$price, main = "wykres pudełkowy dla zmiennej price", 
        xlab = "price", ylab = "Wartości", 
        col = "cyan3", border = "darkslateblue", outline = TRUE, lwd = 1.2)
#Wyniki analizy statystycznej jasno wskazują, że nasze dane nie zawierają skrajnych ani nielogicznych wartości. Ten pozytywny wniosek pozwala nam na pewne podejście do dalszych analiz, mając pewność co do integralności naszych danych.

```

```{r}
plot(agencja_nieruchomosci$price, agencja_nieruchomosci$area_m2,  type = "o", col = "cyan3",
      main = "Wykres obserwacji dla zmiennej Cena",
     xlab = "Obserwacja", ylab = "Cena"     )

```
```{r}
ggplot(agencja_nieruchomosci, aes(x=price, y=after_stat(density))) + geom_histogram(fill= "darkslateblue", bins=30, color="cyan3") + geom_density(color="red", size=1)

ggplot(agencja_nieruchomosci, aes(x=Cena_za_m2, y=after_stat(density))) + geom_histogram(fill= "darkslateblue", bins=30, color="cyan3") + geom_density(color="red", size=1)

#Pokazanie rozkładu cen mieszkań oraz ceny za m2 na histogramie wraz z linią gęstości. 
```
```{r}
ggplot(agencja_nieruchomosci, aes(x=price, y=area_m2, color=bedrooms)) + geom_point() + scale_x_log10() + scale_y_log10() + theme_classic()
#Ilustracja rozkładu ceny nieruchomości na podstawie jej powierzchni, na wykresie mamy także podział na ilość pokojów. To wszystko mamy na zlogarytmowanej skali.
```

```{r}
ggplot(agencja_nieruchomosci, aes(price)) + geom_boxplot(aes(fill=factor(bedrooms))) + facet_wrap(bedrooms) +   labs(title="Rozkład cen nieruchomości w zależności od liczby sypialni")

ggplot(agencja_nieruchomosci, aes(price)) + geom_boxplot(aes(fill=factor(bathrooms))) + facet_wrap(bathrooms) +   labs(title="Rozkład cen nieruchomości w zależności od liczby łazienek")

ggplot(agencja_nieruchomosci, aes(price)) + geom_boxplot(aes(fill=factor(stories))) + facet_wrap(stories) +   labs(title="Rozkład cen nieruchomości w zależności od liczby pięter")

#Zilustrowanie na wykresach box plot zależności rozkładu ceny od wybranej zmiennej
```

```{r}
willa <- agencja_nieruchomosci %>%
  filter(area_m2 >=1000, prefarea=="yes")
#Wyszukanie najtańszej willi (powierzchnia powyżej 1000m2 i w preferowanej okolicy)

ggplot(willa, aes(x=price, y=Cena_za_m2)) + geom_point(size=3, color="cyan3")

#Rozkład willi na wykresie ceny i ceny za m2
  
```

```{r}
ggplot(agencja_nieruchomosci, aes(x=price, y=area_m2, color=furnishingstatus)) + geom_point() + facet_wrap(parking) + labs(title="Rozkład cen nieruchomości w zależności od powierzchni z podziałem na ilość miejsc parkingowych i rozróżnieniem na status umeblowania")

  
```

```{r}
## Pytania badawcze, hipotezy
# Cena mieszkania jest uzależniona od jego powierzchnii
# Cena za m2 uzależniona od preferowanej lokalizacji/umeblowania
# Cena mieszkania uzależniona od ilości sypilani/łazienek/pokoi gościnnych

# ggbetweenstats(data=dane, x=jakościowy, y=ilosciowy)
# ggpiestats -> ggbarstats (x=ryzyko, y=wyksztalcenie, data=dane)

install.packages("ggstatsplot")
library(ggstatsplot)
ggbetweenstats(data=agencja_nieruchomosci, x= furnishingstatus, y=area_m2)
install.packages("rstantools")
library(rstantools)

```